[tools]
prek = "latest"

[settings]
minimum_release_age = "7d"

[tasks.prepare]
description = "Prepare development environment"
run = "prek install"

[tasks.lint]
description = "Run linters to check for issues"
run = "prek run --all-files --color always"

[tasks.update]
description = "Check for updates to the development environment"
run = [
    "prek update --freeze --dry-run",
    "mise upgrade --bump --local --dry-run",
]
