[update]
cooldown_days = 7
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "detect-private-key" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "fa412071e4f5d44d44f9e365f4676f9df92456a2"
hooks = [
  { id = "zizmor" }
]

[[repos]]
repo = "https://github.com/google/yamlfmt"
rev = "21ca5323a9c87ee37a434e0ca908efc0a89daa07"
hooks = [
  { id = "yamlfmt", pass_filenames = false }
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "nix-flake"
name = "nix flake check"
language = "system"
entry = "nix flake check --all-systems --no-build"
pass_filenames = false
